"""
Django settings for qrate_api project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from corsheaders.defaults import default_headers
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#rke%w0p+!axn3-3jjoe7^&dj4)lkz6(^5)id@hj*5p)dwt*!#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.44", "localhost"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "oauth2_provider",
    "qr",
    "organization",
    "account.apps.AccountConfig",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "account.authentication.CookieOrHeaderOAuth2Authentication",
    ]
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "qrate_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qrate_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "qrate-db",
        "USER": "postgres",
        "PASSWORD": "15264859",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

def _split_csv(value):
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


FRONTEND_ORIGINS = _split_csv(config("FRONTEND_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173,http://192.168.0.44:5173"))

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-application-name",
]

AUTH_COOKIE_ACCESS_NAME = config("AUTH_COOKIE_ACCESS_NAME", "access_token")
AUTH_COOKIE_REFRESH_NAME = config("AUTH_COOKIE_REFRESH_NAME", "refresh_token")
AUTH_COOKIE_ACCESS_MAX_AGE_SECONDS = int(config("AUTH_COOKIE_ACCESS_MAX_AGE_SECONDS", "900"))
AUTH_COOKIE_REFRESH_MAX_AGE_SECONDS = int(config("AUTH_COOKIE_REFRESH_MAX_AGE_SECONDS", str(60 * 60 * 24 * 7)))
AUTH_COOKIE_SAMESITE = config("AUTH_COOKIE_SAMESITE", None)
AUTH_COOKIE_SECURE = config("AUTH_COOKIE_SECURE", "true").lower() == "true"
CSRF_COOKIE_NAME = config("CSRF_COOKIE_NAME", "csrf_token")
CSRF_COOKIE_AGE = int(config("CSRF_COOKIE_AGE", "31449600"))
CSRF_COOKIE_PATH = config("CSRF_COOKIE_PATH", "/")
CSRF_COOKIE_DOMAIN=None
CSRF_COOKIE_HTTPONLY = config("CSRF_COOKIE_HTTPONLY", "false").lower() == "true"
CSRF_COOKIE_SAMESITE = AUTH_COOKIE_SAMESITE
CSRF_COOKIE_SECURE = AUTH_COOKIE_SECURE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
