# Generated by Django 4.2.28 on 2026-02-22 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="org_identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
