# Generated by Django 4.2.28 on 2026-02-22 02:22

from django.db import migrations

import uuid

def gen_uuid(apps, schema_editor):
    Organization = apps.get_model("organization", "Organization")
    for row in Organization.objects.all():
        row.org_identifier = uuid.uuid4()
        row.save(update_fields=["org_identifier"])


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_organization_org_identifier"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
