# Generated by Django 4.2.28 on 2026-02-22 02:22

import uuid

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="org_identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

